//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradera.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsUnsubscribed { get; set; }
        public Nullable<System.DateTime> UnsubscribeDate { get; set; }
        public int ClubId { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
