//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradera.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradingTabs
    {
        public int Id { get; set; }
        public int ClubId { get; set; }
        public string Content { get; set; }
        public System.DateTime LastEdited { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
